### ISSUE TITLE
加载两种以上布局内容的问题

### ISSUE THREAD

**Issue by staticzh** [gongwen/MarqueeViewLibrary#1]
![image](https://cloud.githubusercontent.com/assets/19554961/21493173/0f0eab6a-cc45-11e6-91ea-ee43b94f9367.png)
这个位置如果我想要主标题和副标题各显示一个数组中的内容，好像没有区分开来的方法吧，重写的generateMarqueeItemView方法中的参数只是String 类型，所以布局中如果要给不同的控件加载不同的动态内容，不知道楼主实现没有

**Comment by gongwen** [comment]
是支持的，generateMarqueeItemView方法的参数是继承MarqueeFactory时，通过泛型指定的，你只需要修改对应泛型的类型，这样就可以提供你所需要的数据类型，你可以看下[ComplexViewMF.java](https://github.com/gongwen/MarqueeViewLibrary/blob/master/app/src/main/java/com/gw/marquee/ComplexViewMF.java)

**Comment by staticzh** [comment]
好的，我看看，多谢
2016-12-27 

staticzh 



发件人：龚文 <notifications@github.com>
发送时间：2016-12-27 17:41
主题：Re: [gongwen/MarqueeViewLibrary] 加载两种以上布局内容的问题 (#1)
收件人："gongwen/MarqueeViewLibrary"<MarqueeViewLibrary@noreply.github.com>
抄送："staticzh"<staticzh@126.com>,"Author"<author@noreply.github.com>

是支持的，generateMarqueeItemView方法的参数是继承MarqueeFactory时，通过泛型指定的，你只需要修改对应泛型的类型，这样就可以提供你所需要的数据类型，你可以看下ComplexViewMF.java
