### ISSUE TITLE
在fragment中使用报marqueeFactory空指针异常

### ISSUE THREAD

**Issue by dcl1994** [gongwen/MarqueeViewLibrary#14]

**Comment by dcl1994** [comment]
//文字向上翻转
        MarqueeFactory<TextView,String> marqueeFactory=new NoticeMF(getActivity());
        //MarqueeView设置Factory
        marqueeView.setMarqueeFactory(marqueeFactory);
        //开始翻转
        marqueeView.startFlipping();

是不是不能在fragment中使用这个控件？

**Comment by gongwen** [comment]
是可以在fragment中使用的，能提供报错的具体日志嘛
