### ISSUE TITLE
NestedScrollView

### ISSUE THREAD

**Issue by tenSunFree** [gongwen/MarqueeViewLibrary#19]
![2017-09-23_123447](https://user-images.githubusercontent.com/23090085/30770143-bb3b3b52-a05b-11e7-8051-3b73e5ad4df2.jpg)

請教一下, 使用NestedScrollView的原因 是什麼? 
因為似乎也沒有畫面滑動的必要, 還是我忽略了什麼?

**Comment by gongwen** [comment]
因为之前demo里示例较多，一屏显示不下，所以就用了NestedScrollView
