### ISSUE TITLE
和项目冲突了

### ISSUE THREAD

**Issue by msn465780** [gongwen/MarqueeViewLibrary#20]
compile 'com.gongwen:marqueelibrary:1.1.1'

这样添加后，报错，
Error:Execution failed for task ':show_entry:processDebugManifest'.
> Manifest merger failed : Attribute application@label value=(@string/application_name) from AndroidManifest.xml:17:9-49
	is also present at [com.gongwen:marqueelibrary:1.1.1] AndroidManifest.xml:13:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:13:5-1144:19 to override.

**Comment by gongwen** [comment]
这个问题是因为项目名称和引用项目的名称冲突，
解决方法:
manifest加上 xmlns:tools="http://schemas.android.com/tools"
application加上tools:replace="android:label"
