### ISSUE TITLE
请问可以做到文字长度超出控件宽度才滚动，文字长度不超出控件宽度不滚动吗？

### ISSUE THREAD

**Issue by wanglu123run** [gongwen/MarqueeViewLibrary#26]

**Comment by gongwen** [comment]
这个暂时不支持

**Comment by gongwen** [comment]
你描述的这个用TextView设置以下属性
android:singleLine="true"  
android:ellipsize="marquee"  
android:marqueeRepeatLimit="marquee_forever"可以实现
