### ISSUE TITLE
怎么在类里面设置让它INVISIBLE或者GONE，我直接设置之后字隐藏了，但是背景没隐藏起来

### ISSUE THREAD

**Issue by o0ohh** [gongwen/MarqueeViewLibrary#28]
怎么在类里面设置让它INVISIBLE或者GONE，我直接设置之后字隐藏了，但是背景没隐藏起来

**Comment by gongwen** [comment]
你设的是SimpleMarqueeView的背景，还是其父View的背景，可以把代码发一下吗？

**Comment by o0ohh** [comment]
不好意思，回复晚了，我是在xml里的SimpleMarqueeView设置的背景颜色，然后在类里面调用setVisibility(VIEW.INVISIBLE)或者VIEW.GONE之后，字都会消失，但是背景颜色还是在那边。。。后面尝试了下改成selector的背景，然后调用setSelected来控制背景颜色，目前是会隐藏起来了，如果您有更好的方法可以告诉我下，非常感谢

**Comment by gongwen** [comment]
应该不会出现这种情况的，方便加下qq吗，详细说下，1798550470
